import torsh from "/public/images/company/torsh.png";
import vouzot from "/public/images/company/vouzot.png";
import pasteui from "/public/images/company/pasteui.png";

import jason_humphrey from "/public/images/testimonials/jason-humphrey.png";

export const userData = {
  githubUsername: "treyrader11",
  name: "Trey Rader",
  designation: "Full-Stack Developer",
  avatarUrl: "/avatar.png",
  email: "developertrey@gmail.com",
  phone: "504-756-4538",
  address: "New Orleans, Louisiana.",
  resumeUrl:
    "https://drive.google.com/file/d/1gKLk8XPCJCyjnEgEHS4AcKDPm5TDAjDS/view?usp=sharing",
  socialLinks: {
    instagram: "https://instagram.com",
    twitter: "https://twitter.com",
    linkedin: "https://linkedin.com/in/trey-rader",
    github: "https://github.com/treyrader11",
    facebook: "https://facebook.com/",
  },
  about: {
    title:
      "I'm a software developer who loves building products and web applications that impact the world",
    description: [
      `I began teaching myself to code back in 2016, HTML, CSS, and JS. I did well enough to eventually land my first job with an ed tech startup out of New Orleans, called TORSH. After having at TORSH, however, I hardly did anything tech-related except for develop and deploy a few websites for my musician friends`,
      `I've worked in React, Angular, Meteor, Svelte, Node.js, Express, KeystoneJS, MongoDB, MySQL, Prisma, Drizzle, Bootstrap, & Tailwind, to name a few. As of lately, most of my experience has been cosummed in honing in my frontend development skillset using Framer Motion & Gsap, often in tandem.`,
    ],
    current_project_url: "https://www.vouzot.com",
    current_project: "Vouzot",
  },
};

export const projectsData = [
  {
    title: "Musiana",
    desc: "This is just some placeholder text until i make time to actually create the real deal. If you're seeing this, then it means I love you",
    color: "#e3e5e7",
    video_key: "GJyPpc8qaHA",
    // category: "Web Development",
    category: "MERN",
    stack: "MERN",
    technology_feature: [
      "Tailwind",
      "React",
      "Redux",
      "Next js 13",
      "Type Script",
      "Node js",
      "Express js",
      "Firebase",
      "Graphql",
      "Stripe",
    ],
    //   icon: React.createElement(FaReact), //see byte grad
    packages: {
      frontend: [
        "@reduxjs/toolkit",
        "@uiball/loaders",
        "firebase",
        "firebase-admin",
        "nextjs-progressbar",
        "openai",
        "react-firebase-hooks",
        "react-icons",
        "react-redux",
        "react-simple-typewriter",
      ],
      backend: [
        "@reduxjs/toolkit",
        "@uiball/loaders",
        "firebase",
        "firebase-admin",
        "nextjs-progressbar",
        "openai",
        "react-firebase-hooks",
        "react-icons",
        "react-redux",
        "react-simple-typewriter",
      ],
    },
    env: {
      frontend: [
        "VITE_APP_BACKEND_URL",
        "VITE_APP_CLOUD_NAME",
        "VITE_APP_GOOGLE_CLIENT_ID",
        "VITE_APP_GOOGLE_CLIENT_SECRET",
        "VITE_APP_FIREBASE_KEY",
      ],
      backend: [
        "CLOUD_API_KEY",
        "CLOUD_API_SECRET",
        "CLOUD_NAME",
        "JWT_LIFETIME",
        "JWT_SECRET",
        "MONGO_URI",
        "MODE",
        "PORT",
        "EMAIL_HOST",
        "EMAIL_USER",
        "EMAIL_PASS",
        "GOOGLE_CLIENT_SECRET",
        "CRYPTR_KEY",
        "GOOGLE_CLIENT_ID",
        "FRONTEND_URL",
      ],
    },
    youtube_link: "https://youtu.be/yF1oJ7wzvWY",
    githhub_link: "https://github.com/treyrader11/musiana-client",
    download_links: {
      frontend:
        "https://github.com/treyrader11/Vouzot/archive/refs/heads/main.zip",
      backend:
        "https://github.com/treyrader11/musiana-server/archive/refs/heads/main.zip",
    },
    project_image: "c2.png",
    image: {
      isPriority: true,
      src: "c2.png",
    },
    website_url: "https://musiana.vercel.app",
    isRecent: true,
  },
  {
    title: "Vouzot",
    desc: "This is just some placeholder text until i make time to actually create the real deal. If you're seeing this, then it means I love you",
    color: "#d6d7dc",
    isPriority: false,
    video_key: "QKGIvW886dc",
    stack: "Next JS",
    category: "Next JS",
    technology_feature: [
      "Tailwind CSS",
      "Next JS 14 (App Router)",
      "Zustand",
      "TypeScript",
      "Zod",
      "React Hook Form",
      "Prisma",
      "Mongodb",
      "Shadcn UI",
      "Framer Motion",
      "Gsap",
      "Tanstack Table",
      "Stripe JS",
      "Stroybook",
      "Docker",
    ],
    packages: {
      frontend: [
        "@reduxjs/toolkit",
        "@uiball/loaders",
        "firebase",
        "firebase-admin",
        "nextjs-progressbar",
        "openai",
        "react-firebase-hooks",
        "react-icons",
        "react-redux",
        "react-simple-typewriter",
      ],
    },
    env: {
      frontend: [
        "DATABASE_URL",
        "DIRECT_URL",
        "GITHUB_CLIENT_ID",
        "GITHUB_CLIENT_SECRET",
        "GITHUB_AUTH_TOKEN",
        "GOOGLE_CLIENT_ID",
        "GOOGLE_CLIENT_SECRET",
        "AUTH_SECRET",
        "RESEND_API_KEY",
        "NEXT_PUBLIC_APP_URL",
      ],
    },
    youtube_link: "https://youtu.be/AxQ_Eli8gtk",
    githhub_link: "https://github.com/treyrader11/JSearch-Expo",
    download_links: {
      frontend:
        "https://github.com/treyrader11/Vouzot/archive/refs/heads/main.zip",
    },
    project_image: "decimal.png",
    image: {
      isPriority: true,
      src: "decimal.png",
    },
    project_Img_Mobile: [
      "/deliveroo1.jpg",
      "/roo2.jpg",
      "/roo3.jpg",
      "/roo4.jpg",
      "/roo5.jpg",
    ],
  },
  {
    title: "Paste UI",
    desc: "This is just some placeholder text until i make time to actually create the real deal. If you're seeing this, then it means I love you",
    color: "#e3e3e3",
    isPriority: true,
    video_key: "zHL1eT87OCw",
    // category: "UI/UX Design",
    stack: "Next JS",
    category: "Next JS",
    technology_feature: [
      "Tailwind",
      "React",
      "Redux",
      "Next js 13",
      "Type Script",
      "Node js",
      "Express js",
      "Firebase",
      "Graphql",
      "Stripe",
    ],
    packages: {
      frontend: [
        "@reduxjs/toolkit",
        "@uiball/loaders",
        "firebase",
        "firebase-admin",
        "nextjs-progressbar",
        "openai",
        "react-firebase-hooks",
        "react-icons",
        "react-redux",
        "react-simple-typewriter",
      ],
    },
    env: {
      frontend: [
        "DATABASE_URL",
        "DIRECT_URL",
        "GITHUB_CLIENT_ID",
        "GITHUB_CLIENT_SECRET",
        "GITHUB_AUTH_TOKEN",
        "GOOGLE_CLIENT_ID",
        "GOOGLE_CLIENT_SECRET",
        "AUTH_SECRET",
        "RESEND_API_KEY",
        "NEXT_PUBLIC_APP_URL",
      ],
    },
    youtube_link: "https://youtu.be/yF1oJ7wzvWY",
    githhub_link: "https://github.com/treyrader11/JSearch-Expo",
    download_links: {
      frontend:
        "https://github.com/treyrader11/PasteUI/archive/refs/heads/main.zip",
    },
    project_image: "funny.png",
    image: {
      isPriority: true,
      src: "funny.png",
    },
    website_url: "https://www.pasteui.io",
    isRecent: true,
  },
  {
    title: "Leetcode Clone",
    desc: "This is just some placeholder text until i make time to actually create the real deal. If you're seeing this, then it means I love you",
    color: "#21242b",
    isPriority: false,
    video_key: "iT6ahO0CHtM",
    // category: "UI/UX Design",
    stack: "MERN",
    category: "MERN",
    technology_feature: [
      "html",
      "css",
      "Tailwind",
      "React",
      "Redux",
      "Next js 13",
      "Type Script",
      "Firebase",
    ],
    packages: {
      frontend: [
        "@reduxjs/toolkit",
        "@uiball/loaders",
        "firebase",
        "firebase-admin",
        "nextjs-progressbar",
        "openai",
        "react-firebase-hooks",
        "react-icons",
        "react-redux",
        "react-simple-typewriter",
      ],
      backend: [
        "@reduxjs/toolkit",
        "@uiball/loaders",
        "firebase",
        "firebase-admin",
        "nextjs-progressbar",
        "openai",
        "react-firebase-hooks",
        "react-icons",
        "react-redux",
        "react-simple-typewriter",
      ],
    },
    env: {
      frontend: [
        "DATABASE_URL",
        "DIRECT_URL",
        "GITHUB_CLIENT_ID",
        "GITHUB_CLIENT_SECRET",
        "GITHUB_AUTH_TOKEN",
        "GOOGLE_CLIENT_ID",
        "GOOGLE_CLIENT_SECRET",
        "AUTH_SECRET",
        "RESEND_API_KEY",
        "NEXT_PUBLIC_APP_URL",
      ],
      backend: [
        "DATABASE_URL",
        "DIRECT_URL",
        "GITHUB_CLIENT_ID",
        "GITHUB_CLIENT_SECRET",
        "GITHUB_AUTH_TOKEN",
        "GOOGLE_CLIENT_ID",
        "GOOGLE_CLIENT_SECRET",
        "AUTH_SECRET",
        "RESEND_API_KEY",
        "NEXT_PUBLIC_APP_URL",
      ],
    },
    youtube_link: "https://youtu.be/R90bxY4UwPg",
    githhub_link: "https://github.com/treyrader11/JSearch-Expo",
    download_links: {
      frontend:
        "https://github.com/treyrader11/JSearch-Expo/archive/refs/heads/main.zip",
      backend:
        "https://github.com/treyrader11/JSearch-Expo/archive/refs/heads/main.zip",
    },
    project_image: "google.png",
    image: {
      isPriority: true,
      src: "google.png",
    },
    website_url: "",
    isRecent: false,
  },
  {
    title: "UTube Study",
    desc: "This is just some placeholder text until i make time to actually create the real deal. If you're seeing this, then it means I love you",
    color: "#ec4e39",
    video_key: "dX3WaXJ9ibw",
    category: "MERN",
    technology_feature: [
      "Tailwind",
      "React",
      "Redux",
      "Next js 13",
      "Type Script",
      "Node js",
      "Express js",
      "Postger sql",
      "Firebase",
      "Stripe",
    ],
    packages: {
      frontend: [
        "@reduxjs/toolkit",
        "@uiball/loaders",
        "firebase",
        "firebase-admin",
        "nextjs-progressbar",
        "openai",
        "react-firebase-hooks",
        "react-icons",
        "react-redux",
        "react-simple-typewriter",
      ],
      backend: [
        "@reduxjs/toolkit",
        "@uiball/loaders",
        "firebase",
        "firebase-admin",
        "nextjs-progressbar",
        "openai",
        "react-firebase-hooks",
        "react-icons",
        "react-redux",
        "react-simple-typewriter",
      ],
    },
    env: {
      frontend: [
        "DATABASE_URL",
        "DIRECT_URL",
        "GITHUB_CLIENT_ID",
        "GITHUB_CLIENT_SECRET",
        "GITHUB_AUTH_TOKEN",
        "GOOGLE_CLIENT_ID",
        "GOOGLE_CLIENT_SECRET",
        "AUTH_SECRET",
        "RESEND_API_KEY",
        "NEXT_PUBLIC_APP_URL",
      ],
      backend: [
        "DATABASE_URL",
        "DIRECT_URL",
        "GITHUB_CLIENT_ID",
        "GITHUB_CLIENT_SECRET",
        "GITHUB_AUTH_TOKEN",
        "GOOGLE_CLIENT_ID",
        "GOOGLE_CLIENT_SECRET",
        "AUTH_SECRET",
        "RESEND_API_KEY",
        "NEXT_PUBLIC_APP_URL",
      ],
    },
    youtube_link: "https://youtu.be/v3LJMcWbcDQ",
    githhub_link: "https://github.com/treyrader11/JSearch-Expo",
    download_links: {
      frontend:
        "https://github.com/treyrader11/JSearch-Expo/archive/refs/heads/main.zip",
      backend:
        "https://github.com/treyrader11/JSearch-Expo/archive/refs/heads/main.zip",
    },
    project_image: "maven.png",
    image: {
      isPriority: true,
      src: "maven.png",
    },
    website_url: "",
    isRecent: true,
  },
  {
    title: "Logo Maker",
    desc: "This is just some placeholder text until i make time to actually create the real deal. If you're seeing this, then it means I love you",
    color: "#e1dad6",
    video_key: "PyaAp-eANRQ",
    category: "React Native",
    technology_feature: [
      "html",
      "css",
      "Javascript",
      "Tailwind",
      "React",
      "Redux",
      "Three js",
      "Framer Motion",
    ],
    packages: {
      frontend: [
        "@reduxjs/toolkit",
        "@uiball/loaders",
        "firebase",
        "firebase-admin",
        "nextjs-progressbar",
        "openai",
        "react-firebase-hooks",
        "react-icons",
        "react-redux",
        "react-simple-typewriter",
      ],
      backend: [
        "@reduxjs/toolkit",
        "@uiball/loaders",
        "firebase",
        "firebase-admin",
        "nextjs-progressbar",
        "openai",
        "react-firebase-hooks",
        "react-icons",
        "react-redux",
        "react-simple-typewriter",
      ],
    },
    env: {
      frontend: [
        "DATABASE_URL",
        "DIRECT_URL",
        "GITHUB_CLIENT_ID",
        "GITHUB_CLIENT_SECRET",
        "GITHUB_AUTH_TOKEN",
        "GOOGLE_CLIENT_ID",
        "GOOGLE_CLIENT_SECRET",
        "AUTH_SECRET",
        "RESEND_API_KEY",
        "NEXT_PUBLIC_APP_URL",
      ],
      backend: [
        "DATABASE_URL",
        "DIRECT_URL",
        "GITHUB_CLIENT_ID",
        "GITHUB_CLIENT_SECRET",
        "GITHUB_AUTH_TOKEN",
        "GOOGLE_CLIENT_ID",
        "GOOGLE_CLIENT_SECRET",
        "AUTH_SECRET",
        "RESEND_API_KEY",
        "NEXT_PUBLIC_APP_URL",
      ],
    },
    youtube_link: "https://youtu.be/6wzf2ho-kzI",
    githhub_link: "https://github.com/treyrader11/JSearch-Expo",
    download_links: {
      frontend:
        "https://github.com/treyrader11/PasteUI/archive/refs/heads/main.zip",
      backend:
        "https://github.com/treyrader11/PasteUI/archive/refs/heads/main.zip",
    },
    project_image: "panda.png",
    image: {
      isPriority: true,
      src: "panda.png",
    },
    website_url: "",
    isRecent: false,
  },
];

export const references = [
  {
    image_url: jason_humphrey,
    desc: "If given the opportunity I would hire Trey for any of my coding needs. I know that he will be an excellent addition to any prospective company in the near future.",
    name: "Jason Humphrey",
    title: "Senior Developer, Nike",
  },
  {
    image_url: jason_humphrey,
    desc: "If given the opportunity I would hire Trey for any of my coding needs. I know that he will be an excellent addition to any prospective company in the near future.",
    name: "Wilson Savoy",
    title: "Musician, Pine Leaf Boys",
  },
  {
    image_url: jason_humphrey,
    desc: "If given the opportunity I would hire Trey for any of my coding needs. I know that he will be an excellent addition to any prospective company in the near future.",
    name: "Daniel Dekerlegand",
    title: "Senior Developer, Evolve",
  },
  {
    image_url: jason_humphrey,
    desc: "If given the opportunity I would hire Trey for any of my coding needs. I know that he will be an excellent addition to any prospective company in the near future.",
    name: "Janine Bonilla",
    title: "Marketing Director, Nasty",
  },
];

export const experiences = [
  {
    title: "Meteor JS Developer",
    company_name: "Torsh",
    icon: torsh,
    iconBg: "#E6DEDD",
    date: "April 2017 - August 2018",
    website_url: "https://www.torsh.co",
    points: [
      "Developed features in a large fullstack web application and separate corporate CMS website. Integrated 3rd party APIs into platform. Wrote server side CRUD methods and implementing frontend UI and UX.",
      "Architected features from design mocks. Communicated with UX designer to clarify feature behavior.",
      "Coordinated with other developers to complete sprints. Collaborated using version control to organize workflow. Discussed sprint progress during scrum meetings and engaged in peer reviews. Presented work during weekly demos.",
      "Corresponded with other developers via Slack and Google Hangouts. Collaborated on software development projects in realtime using screenshare software.",
      "Experienced with manual acceptance testing for large software releases. Automated testing experience. Tracked bugs by opening and resolving sprint cases.",
      "Drafted, composed, and edited technical documentation to meet purpose and standards.",
    ],
  },
  {
    title: "Founder/Sr. React JS Developer",
    company_name: "Vouzot",
    icon: vouzot,
    iconBg: "#7900B6",
    date: "August 2022 - Present",
    website_url: "https://www.vouzot.com",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    title: "Founder/Sr. React JS Developer",
    company_name: "Paste UI",
    icon: pasteui,
    iconBg: "#383E56",
    date: "Jan 2024 - Present",
    website_url: "https://www.pasteui.io",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
];

export const skillsData = [
  {
    skill_name: "Html 5",
    Image: "/html.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Css",
    Image: "/css.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "JavaScript",
    Image: "/js.png",
    width: 65,
    hight: 65,
  },
  {
    skill_name: "Tailwind CSS",
    Image: "/tailwind.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "React",
    Image: "/react.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Redux",
    Image: "/redux.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Tanstack React Query",
    Image: "/reactquery.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "TypeScript",
    Image: "/ts.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Next js 13",
    Image: "/next.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Next Auth",
    Image: "https://next-auth.js.org/img/logo/logo-sm.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "JSON Web Tocken",
    Image:
      "https://seeklogo.com/images/J/json-web-tokens-jwt-io-logo-C003DEC47A-seeklogo.com.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Framer Motion",
    Image: "/framer.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Stripe Payment",
    Image: "/stripe.webp",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Node js",
    Image: "/node-js.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Express js",
    Image: "/express.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Mongo db",
    Image: "/mongodb.png",
    width: 40,
    hight: 40,
  },
  {
    skill_name: "Firebase",
    Image: "/Firebase.png",
    width: 55,
    hight: 55,
  },
  {
    skill_name: "Postger SQL",
    Image: "/postger.png",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "My SQL",
    Image: "/mysql.png",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Prisma",
    Image: "/prisma.webp",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Graphql",
    Image: "/graphql.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "React Native",
    Image: "/ReactNative .png",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Docker",
    Image: "/docker.webp",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Figma",
    Image: "/figma.png",
    width: 50,
    hight: 50,
  },
  {
    skill_name: "Web Socket",
    Image: "https://avatars.githubusercontent.com/u/10566080?s=200&v=4",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Cloundary",
    Image: "https://cdn.worldvectorlogo.com/logos/cloudinary-2.svg",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Meteor js",
    Image: "https://raw.githubusercontent.com/gin-gonic/logo/master/color.png",
    width: 50,
    hight: 50,
  },
  {
    skill_name: "Git",
    Image: "https://git-scm.com/images/logos/downloads/Git-Icon-1788C.png",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Npm",
    Image: "https://authy.com/wp-content/uploads/npm-logo.png",
    width: 70,
    hight: 70,
  },
];

export const frontendSkills = [
  {
    skill_name: "Html 5",
    Image: "/html.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "CSS",
    Image: "/css.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "JavaScript",
    Image: "/js.png",
    width: 65,
    hight: 65,
  },
  {
    skill_name: "Tailwind CSS",
    Image: "/tailwind.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Material UI",
    Image: "/mui.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "React",
    Image: "/react.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Redux",
    Image: "/redux.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Tanstack React Query",
    Image: "/reactquery.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Zod",
    Image: "/reactquery.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Type Script",
    Image: "/ts.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Next js",
    Image: "/next.png",
    width: 80,
    hight: 80,
  },
];

export const backendSkills = [
  {
    skill_name: "Node js",
    Image: "/node-js.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Express js",
    Image: "/express.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Mongo db",
    Image: "/mongodb.png",
    width: 40,
    hight: 40,
  },
  {
    skill_name: "Fire base",
    Image: "/Firebase.png",
    width: 55,
    hight: 55,
  },
  {
    skill_name: "Postger SQL",
    Image: "/postger.png",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "My SQL",
    Image: "/mysql.png",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Prisma",
    Image: "/prisma.webp",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Graphql",
    Image: "/graphql.png",
    width: 80,
    hight: 80,
  },
];

export const fullstackSkills = [
  {
    skill_name: "React Native",
    Image: "/ReactNative .png",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Docker",
    Image: "/docker.webp",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Nigx",
    Image:
      "https://i0.wp.com/thinkground.studio/wp-content/uploads/2019/04/190415_Nginx-Logo.png?fit=423%2C401&ssl=1",
    width: 60,
    hight: 60,
  },
  {
    skill_name: "Figma",
    Image: "/figma.png",
    width: 50,
    hight: 50,
  },
  {
    skill_name: "Web Scoket",
    Image: "https://avatars.githubusercontent.com/u/10566080?s=200&v=4",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Gin gonic",
    Image: "https://raw.githubusercontent.com/gin-gonic/logo/master/color.png",
    width: 50,
    hight: 50,
  },
];

export const otherSkills = [
  {
    skill_name: "Next Auth",
    Image: "https://next-auth.js.org/img/logo/logo-sm.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Json Web Tocken",
    Image:
      "https://seeklogo.com/images/J/json-web-tokens-jwt-io-logo-C003DEC47A-seeklogo.com.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Framer Motion",
    Image: "/framer.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Stripe Payment",
    Image: "/stripe.webp",
    width: 80,
    hight: 80,
  },
];

export const other_skill2 = [
  {
    skill_name: "Cloundary",
    Image: "https://cdn.worldvectorlogo.com/logos/cloudinary-2.svg",
    width: 70,
    hight: 70,
  },

  {
    skill_name: "Git",
    Image: "https://git-scm.com/images/logos/downloads/Git-Icon-1788C.png",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Npm",
    Image: "https://authy.com/wp-content/uploads/npm-logo.png",
    width: 70,
    hight: 70,
  },
];
export const otherSkills3 = [
  {
    skill_name: "Go",
    Image: "/go.png",
    width: 60,
    hight: 60,
  },
];
