import torsh from "/public/images/company/torsh.png";
import vouzot from "/public/images/company/vouzot.png";
import pasteui from "/public/images/company/pasteui.png";

import jason_humphrey from "/public/images/testimonials/jason-humphrey.png";

export const userData = {
  githubUsername: "treyrader11",
  name: "Trey Rader",
  designation: "Full-Stack Developer",
  avatarUrl: "/avatar.png",
  email: "developertrey@gmail.com",
  phone: "504-756-4538",
  address: "New Orleans, Louisiana.",
  resumeUrl:
    "https://drive.google.com/file/d/1gKLk8XPCJCyjnEgEHS4AcKDPm5TDAjDS/view?usp=sharing",
  socialLinks: {
    instagram: "https://instagram.com",
    twitter: "https://twitter.com",
    linkedin: "https://linkedin.com/in/trey-rader",
    github: "https://github.com/treyrader11",
    facebook: "https://facebook.com/",
  },
  about: {
    title:
      "I'm a software developer who loves building products and web applications that impact the world",
    description: [
      `I began teaching myself to code back in 2016, HTML, CSS, and JS. I did well enough to eventually land my first job with an ed tech startup out of New Orleans, called TORSH. After having at TORSH, however, I hardly did anything tech-related except for develop and deploy a few websites for my musician friends`,
      `I've worked in React, Angular, Meteor, Svelte, Node.js, Express, KeystoneJS, MongoDB, MySQL, Prisma, Drizzle, Bootstrap, & Tailwind, to name a few. As of lately, most of my experience has been cosummed in honing in my frontend development skillset using Framer Motion & Gsap, often in tandem.`,
    ],
    current_project_url: "https://www.vouzot.com",
    current_project: "Vouzot"
  },
};

export const projectsData = [
  {
    title: "Musiana",
    description:
      "Originally hailing from Austria, Berlin-based photographer Matthias Leindinger is a young creative brimming with talent and ideas.",
    link: "https://www.ignant.com/2023/03/25/ad2186-matthias-leidingers-photographic-exploration-of-awe-and-wonder/",
    color: "#e3e5e7",
    isPriority: true,
    video_key: "GJyPpc8qaHA",
    say_hi: "Hi there 🤤",
    category: "Web Development",
    say_hi_blog:
      "Food Shopping Project With Graphql server User Authentication  , Create , Read ,  Update , Delete And Google login , Github , Instgram , Facebook , JWT Auth  ",
    technology_feature: [
      "Tailwind",
      "React",
      "Redux",
      "Next js 13",
      "Type Script",
      "Node js",
      "Express js",
      "Firebase",
      "Graphql",
      "Stripe",
    ],
    //   icon: React.createElement(FaReact), //see byte grad
    about_this_app:
      "A Real Time Full Stack FoodOrder & Admin Dashboard application User Can Order and Contain Payment For Stripe And AdminDashBoard Feature Admin can make Product CRUD and Responsive Desing",
    packages: {
      frontend: [
        "@reduxjs/toolkit",
        "@uiball/loaders",
        "firebase",
        "firebase-admin",
        "nextjs-progressbar",
        "openai",
        "react-firebase-hooks",
        "react-icons",
        "react-redux",
        "react-simple-typewriter",
      ],
      backend: [
        "@reduxjs/toolkit",
        "@uiball/loaders",
        "firebase",
        "firebase-admin",
        "nextjs-progressbar",
        "openai",
        "react-firebase-hooks",
        "react-icons",
        "react-redux",
        "react-simple-typewriter",
      ],
    },
    env: {
      frontend: [
        'DATABASE_URL',
        'DIRECT_URL',
        'GITHUB_CLIENT_ID',
        'GITHUB_CLIENT_SECRET',
        'GITHUB_AUTH_TOKEN',
        'GOOGLE_CLIENT_ID',
        'GOOGLE_CLIENT_SECRET',
        'AUTH_SECRET',
        'RESEND_API_KEY',
        "NEXT_PUBLIC_APP_URL",
      ],
      backend: [
        'DATABASE_URL',
        'DIRECT_URL',
        'GITHUB_CLIENT_ID',
        'GITHUB_CLIENT_SECRET',
        'GITHUB_AUTH_TOKEN',
        'GOOGLE_CLIENT_ID',
        'GOOGLE_CLIENT_SECRET',
        'AUTH_SECRET',
        'RESEND_API_KEY',
        "NEXT_PUBLIC_APP_URL",
      ],
    },
    youtube_link: "https://youtu.be/yF1oJ7wzvWY",
    githhub_link: "https://github.com/treyrader11/JSearch-Expo",
    frontend_download_link:
      "https://github.com/treyrader11/JSearch-Expo/archive/refs/heads/main.zip",
    backend_download_link:
      "https://github.com/treyrader11/JSearch-Expo/archive/refs/heads/main.zip",
    // "https://github.com/HyatMyat4/DeshboardBackend/archive/refs/heads/main.zip",
    project_image: "c2.png",
    project_blog:
      "A Real Time Full Stack FoodOrder & Admin Dashboard application User Can Order and Contain Payment For Stripe And AdminDashBoard Feature Admin can make Product CRUD and",
    Type: "Next js 13",
    indevelopment: false,
    website_url: "https://musiana.vercel.app",
  },
  {
    title: "Vouzot",
    description:
      "This is a story on the border between reality and imaginary, about the contradictory feelings that the insularity of a rocky, arid, and wild territory provokes”—so French photographer Clément Chapillon describes his latest highly captivating project Les rochers fauves (French for ‘The tawny rocks’).",
    link: "https://www.ignant.com/2022/09/30/clement-chapillon-questions-geographical-and-mental-isolation-with-les-rochers-fauves/",
    color: "#d6d7dc",
    isPriority: false,
    video_key: "QKGIvW886dc",
    category: "Mobile Development",
    say_hi: "Hi there 📱",
    say_hi_blog:
      "ReactNative First Project With Expo CLI Conatain Google AUthentication Contain Basic RestApi and Google Maps functionality ",
    technology_feature: [
      "Tailwind CSS",
      "Next JS 14 (App Router)",
      "Zustand",
      "TypeScript",
      "Zod",
      "React Hook Form",
      "Prisma",
      "Mongodb",
      "Shadcn UI",
      "Framer Motion",
      "Gsap",
      "Tanstack Table",
      "Stripe JS",
      "Stroybook",
      "Docker",
    ],
    about_this_app:
      "It My First ReactNative App So The have a lot of Bug!, Feature Conatin Google Auth UserCanOrder Remove Order And Containe ReactNativeMap Justlike Deliveroo",
    packages: {
      frontend: [
        "@reduxjs/toolkit",
        "@uiball/loaders",
        "firebase",
        "firebase-admin",
        "nextjs-progressbar",
        "openai",
        "react-firebase-hooks",
        "react-icons",
        "react-redux",
        "react-simple-typewriter",
      ],
      backend: [
        "@reduxjs/toolkit",
        "@uiball/loaders",
        "firebase",
        "firebase-admin",
        "nextjs-progressbar",
        "openai",
        "react-firebase-hooks",
        "react-icons",
        "react-redux",
        "react-simple-typewriter",
      ],
    },
    env: {
      frontend: [
        'DATABASE_URL',
        'DIRECT_URL',
        'GITHUB_CLIENT_ID',
        'GITHUB_CLIENT_SECRET',
        'GITHUB_AUTH_TOKEN',
        'GOOGLE_CLIENT_ID',
        'GOOGLE_CLIENT_SECRET',
        'AUTH_SECRET',
        'RESEND_API_KEY',
        "NEXT_PUBLIC_APP_URL",
      ],
      backend: [
        'DATABASE_URL',
        'DIRECT_URL',
        'GITHUB_CLIENT_ID',
        'GITHUB_CLIENT_SECRET',
        'GITHUB_AUTH_TOKEN',
        'GOOGLE_CLIENT_ID',
        'GOOGLE_CLIENT_SECRET',
        'AUTH_SECRET',
        'RESEND_API_KEY',
        "NEXT_PUBLIC_APP_URL",
      ],
    },
    youtube_link: "https://youtu.be/AxQ_Eli8gtk",
    githhub_link: "https://github.com/treyrader11/JSearch-Expo",
    frontend_download_link:
      "https://github.com/treyrader11/JSearch-Expo/archive/refs/heads/main.zip",
    backend_download_link:
      "https://github.com/treyrader11/JSearch-Expo/archive/refs/heads/main.zip",
    // "https://github.com/HyatMyat4/Deliveroo/archive/refs/heads/main.zip",
    project_image: "decimal.png",
    project_blog:
      "It My First ReactNative App So The have a lot of Bug!, Feature Conatin Google Auth UserCanOrder Remove Order And Containe ReactNativeMap Justlike Deliveroo",
    Type: "React Native",
    project_Img_Mobile: [
      "/deliveroo1.jpg",
      "/roo2.jpg",
      "/roo3.jpg",
      "/roo4.jpg",
      "/roo5.jpg",
    ],
    indevelopment: false,
  },
  {
    title: "Paste UI",
    description:
      "Though he views photography as a medium for storytelling, Zissou’s images don’t insist on a narrative. Both crisp and ethereal, they’re encoded with an ambiguity—a certain tension—that lets the viewer find their own story within them.",
    link: "https://www.ignant.com/2023/10/28/capturing-balis-many-faces-zissou-documents-the-sacred-and-the-mundane-of-a-fragile-island/",
    color: "#e3e3e3",
    isPriority: true,
    video_key: "zHL1eT87OCw",
    category: "UI/UX Design",
    say_hi: "Xi Form Responsive Food Project🤤",
    say_hi_blog:
      "Food Shopping Project With Graphql server User Authentication  , Create , Read ,  Update , Delete And Google login , Github , Instgram , Facebook , JWT Auth  ",
    technology_feature: [
      "Tailwind",
      "React",
      "Redux",
      "Next js 13",
      "Type Script",
      "Node js",
      "Express js",
      "Firebase",
      "Graphql",
      "Stripe",
    ],

    about_this_app:
      "A Real Time Full Stack FoodOrder & Admin Dashboard application User Can Order and Contain Payment For Stripe And AdminDashBoard Feature Admin can make Product CRUD and Responsive Desing",
    packages: {
      frontend: [
        "@reduxjs/toolkit",
        "@uiball/loaders",
        "firebase",
        "firebase-admin",
        "nextjs-progressbar",
        "openai",
        "react-firebase-hooks",
        "react-icons",
        "react-redux",
        "react-simple-typewriter",
      ],
      backend: [
        "@reduxjs/toolkit",
        "@uiball/loaders",
        "firebase",
        "firebase-admin",
        "nextjs-progressbar",
        "openai",
        "react-firebase-hooks",
        "react-icons",
        "react-redux",
        "react-simple-typewriter",
      ],
    },
    env: {
      frontend: [
        'DATABASE_URL',
        'DIRECT_URL',
        'GITHUB_CLIENT_ID',
        'GITHUB_CLIENT_SECRET',
        'GITHUB_AUTH_TOKEN',
        'GOOGLE_CLIENT_ID',
        'GOOGLE_CLIENT_SECRET',
        'AUTH_SECRET',
        'RESEND_API_KEY',
        "NEXT_PUBLIC_APP_URL",
      ],
      backend: [
        'DATABASE_URL',
        'DIRECT_URL',
        'GITHUB_CLIENT_ID',
        'GITHUB_CLIENT_SECRET',
        'GITHUB_AUTH_TOKEN',
        'GOOGLE_CLIENT_ID',
        'GOOGLE_CLIENT_SECRET',
        'AUTH_SECRET',
        'RESEND_API_KEY',
        "NEXT_PUBLIC_APP_URL",
      ],
    },
    youtube_link: "https://youtu.be/yF1oJ7wzvWY",
    githhub_link: "https://github.com/treyrader11/JSearch-Expo",
    frontend_download_link:
      "https://github.com/treyrader11/JSearch-Expo/archive/refs/heads/main.zip",
    backend_download_link:
      "https://github.com/treyrader11/JSearch-Expo/archive/refs/heads/main.zip",
    project_image: "funny.png",
    project_blog:
      "A Real Time Full Stack FoodOrder & Admin Dashboard application User Can Order and Contain Payment For Stripe And AdminDashBoard Feature Admin can make Product CRUD and",
    Type: "Next js 13",
    indevelopment: false,
    website_url: "",
  },
  {
    title: "Leetcode Clone",
    description:
      "The coastlines of Denmark are documented in tonal colors in a pensive new series by Danish photographers Ulrik Hasemann and Mathias Svold; an ongoing project investigating how humans interact with and disrupt the Danish coast.",
    src: "google.png",
    link: "https://www.ignant.com/2019/03/13/a-photographic-series-depicting-the-uncertain-future-of-denmarks-treasured-coastlines/",
    color: "#21242b",
    isPriority: false,
    video_key: "iT6ahO0CHtM",
    category: "UI/UX Design",
    say_hi: "Hi there 💚",
    say_hi_blog:
      "This is my First AI Project data Coming From Opend AI , You can asked like RealTime Chat GPT   ",
    technology_feature: [
      "html",
      "css",
      "Tailwind",
      "React",
      "Redux",
      "Next js 13",
      "Type Script",
      "Firebase",
    ],

    about_this_app:
      "This Appp Contain Chate Create , Read , Update , Delete and Google Authentication , Microsoft Authentication , JWT Authentication functionality ",
    packages: {
      frontend: [
        "@reduxjs/toolkit",
        "@uiball/loaders",
        "firebase",
        "firebase-admin",
        "nextjs-progressbar",
        "openai",
        "react-firebase-hooks",
        "react-icons",
        "react-redux",
        "react-simple-typewriter",
      ],
      backend: [
        "@reduxjs/toolkit",
        "@uiball/loaders",
        "firebase",
        "firebase-admin",
        "nextjs-progressbar",
        "openai",
        "react-firebase-hooks",
        "react-icons",
        "react-redux",
        "react-simple-typewriter",
      ],
    },
    env: {
      frontend: [
        'DATABASE_URL',
        'DIRECT_URL',
        'GITHUB_CLIENT_ID',
        'GITHUB_CLIENT_SECRET',
        'GITHUB_AUTH_TOKEN',
        'GOOGLE_CLIENT_ID',
        'GOOGLE_CLIENT_SECRET',
        'AUTH_SECRET',
        'RESEND_API_KEY',
        "NEXT_PUBLIC_APP_URL",
      ],
      backend: [
        'DATABASE_URL',
        'DIRECT_URL',
        'GITHUB_CLIENT_ID',
        'GITHUB_CLIENT_SECRET',
        'GITHUB_AUTH_TOKEN',
        'GOOGLE_CLIENT_ID',
        'GOOGLE_CLIENT_SECRET',
        'AUTH_SECRET',
        'RESEND_API_KEY',
        "NEXT_PUBLIC_APP_URL",
      ],
    },
    youtube_link: "https://youtu.be/R90bxY4UwPg",
    githhub_link: "https://github.com/treyrader11/JSearch-Expo",
    frontend_download_link:
      "https://github.com/treyrader11/JSearch-Expo/archive/refs/heads/main.zip",
    backend_download_link:
      "https://github.com/treyrader11/JSearch-Expo/archive/refs/heads/main.zip",
    project_image: "google.png",
    project_blog:
      "A Real Time You Can Ask any thing & you can create new chat delete chat & Clear conversations Feature and google , microsoft Auth",
    Type: "Next js 13",
    indevelopment: false,
    website_url: "",
  },
  {
    title: "UTube Study",
    description:
      "Dutch photographer Mark Rammers has shared with IGNANT the first chapter of his latest photographic project, ‘all over again’—captured while in residency at Hektor, an old farm in Los Valles, Lanzarote. Titled ‘Beginnings’, the mesmerizing collection of images is a visual and meditative journey into the origins of regrets and the uncertainty of stepping into new unknowns.",
    link: "https://www.ignant.com/2023/04/12/mark-rammers-all-over-again-is-a-study-of-regret-and-the-willingness-to-move-forward/",
    color: "#ec4e39",
    isPriority: true,
    video_key: "dX3WaXJ9ibw",
    category: "Web Development",
    say_hi: "Hello my friends 👟",
    say_hi_blog:
      "Xi That is My  Fullstack Responsive Shoes Project I get A lot of SKill Form This Project Complex Ui , authentication , CRUD 💚💚 ",
    technology_feature: [
      "Tailwind",
      "React",
      "Redux",
      "Next js 13",
      "Type Script",
      "Node js",
      "Express js",
      "Postger sql",
      "Firebase",
      "Stripe",
    ],
    about_this_app:
      "A Real Time Full Stack Responsive Shoe Ecommerce & Admin Dashboard application User Can Order and Contain Real World Payment For Stripe And AdminDashBoard Feature Admin can make Product CRUD and Promote Product CRUD Admin Can look How Much User & Chart Pie , Chart line and Auth Google , Nike Auth",
    packages: {
      frontend: [
        "@reduxjs/toolkit",
        "@uiball/loaders",
        "firebase",
        "firebase-admin",
        "nextjs-progressbar",
        "openai",
        "react-firebase-hooks",
        "react-icons",
        "react-redux",
        "react-simple-typewriter",
      ],
      backend: [
        "@reduxjs/toolkit",
        "@uiball/loaders",
        "firebase",
        "firebase-admin",
        "nextjs-progressbar",
        "openai",
        "react-firebase-hooks",
        "react-icons",
        "react-redux",
        "react-simple-typewriter",
      ],
    },
    env: {
      frontend: [
        'DATABASE_URL',
        'DIRECT_URL',
        'GITHUB_CLIENT_ID',
        'GITHUB_CLIENT_SECRET',
        'GITHUB_AUTH_TOKEN',
        'GOOGLE_CLIENT_ID',
        'GOOGLE_CLIENT_SECRET',
        'AUTH_SECRET',
        'RESEND_API_KEY',
        "NEXT_PUBLIC_APP_URL",
      ],
      backend: [
        'DATABASE_URL',
        'DIRECT_URL',
        'GITHUB_CLIENT_ID',
        'GITHUB_CLIENT_SECRET',
        'GITHUB_AUTH_TOKEN',
        'GOOGLE_CLIENT_ID',
        'GOOGLE_CLIENT_SECRET',
        'AUTH_SECRET',
        'RESEND_API_KEY',
        "NEXT_PUBLIC_APP_URL",
      ],
    },
    youtube_link: "https://youtu.be/v3LJMcWbcDQ",
    githhub_link: "https://github.com/treyrader11/JSearch-Expo",
    frontend_download_link:
      "https://github.com/treyrader11/JSearch-Expo/archive/refs/heads/main.zip",
    backend_download_link:
      "https://github.com/treyrader11/JSearch-Expo/archive/refs/heads/main.zip",
    project_image: "maven.png",
    project_blog:
      "This is just some placeholder text until i make time to actually create the real deal. If you're seeing this, then it means I love you",
    Type: "Next js 13",
    indevelopment: false,
    website_url: "",
  },
  {
    title: "Logo Maker",
    description:
      "Dutch photographer Mark Rammers has shared with IGNANT the first chapter of his latest photographic project, ‘all over again’—captured while in residency at Hektor, an old farm in Los Valles, Lanzarote. Titled ‘Beginnings’, the mesmerizing collection of images is a visual and meditative journey into the origins of regrets and the uncertainty of stepping into new unknowns.",
    link: "https://www.ignant.com/2023/04/12/mark-rammers-all-over-again-is-a-study-of-regret-and-the-willingness-to-move-forward/",
    color: "#e1dad6",
    isPriority: false,
    video_key: "PyaAp-eANRQ",
    category: "Web Development",
    say_hi: "Hi there! 👋🏼",
    say_hi_blog:
      "This is just some placeholder text until i make time to actually create the real deal. If you're seeing this, then it means I love you",
    technology_feature: [
      "html",
      "css",
      "Javascript",
      "Tailwind",
      "React",
      "Redux",
      "Three js",
      "Framer Motion",
    ],
    about_this_app:
      "This is just some placeholder text until i make time to actually create the real deal. If you're seeing this, then it means I love you",
    packages: {
      frontend: [
        "@reduxjs/toolkit",
        "@uiball/loaders",
        "firebase",
        "firebase-admin",
        "nextjs-progressbar",
        "openai",
        "react-firebase-hooks",
        "react-icons",
        "react-redux",
        "react-simple-typewriter",
      ],
      backend: [
        "@reduxjs/toolkit",
        "@uiball/loaders",
        "firebase",
        "firebase-admin",
        "nextjs-progressbar",
        "openai",
        "react-firebase-hooks",
        "react-icons",
        "react-redux",
        "react-simple-typewriter",
      ],
    },
    env: {
      frontend: [
        'DATABASE_URL',
        'DIRECT_URL',
        'GITHUB_CLIENT_ID',
        'GITHUB_CLIENT_SECRET',
        'GITHUB_AUTH_TOKEN',
        'GOOGLE_CLIENT_ID',
        'GOOGLE_CLIENT_SECRET',
        'AUTH_SECRET',
        'RESEND_API_KEY',
        // 'NEXT_PUBLIC_APP_URL="http://localhost:3000"',
        "NEXT_PUBLIC_APP_URL",
      ],
      backend: [
        'DATABASE_URL',
        'DIRECT_URL',
        'GITHUB_CLIENT_ID',
        'GITHUB_CLIENT_SECRET',
        'GITHUB_AUTH_TOKEN',
        'GOOGLE_CLIENT_ID',
        'GOOGLE_CLIENT_SECRET',
        'AUTH_SECRET',
        'RESEND_API_KEY',
        "NEXT_PUBLIC_APP_URL",
      ],
    },
    youtube_link: "https://youtu.be/6wzf2ho-kzI",
    githhub_link: "https://github.com/treyrader11/JSearch-Expo",
    frontend_download_link:
      "https://github.com/treyrader11/JSearch-Expo/archive/refs/heads/main.zip",
    backend_download_link:
      "https://github.com/treyrader11/JSearch-Expo/archive/refs/heads/main.zip",
    project_image: "panda.png",
    project_blog: "An app that helps design logos",
    Type: "React",
    indevelopment: false,
    website_url: "",
  },
];

export const references = [
  {
    image_url: jason_humphrey,
    desc: "If given the opportunity I would hire Trey for any of my coding needs. I know that he will be an excellent addition to any prospective company in the near future.",
    name: "Jason Humphrey",
    title: "Senior Developer, Nike",
  },
  {
    image_url: jason_humphrey,
    desc: "If given the opportunity I would hire Trey for any of my coding needs. I know that he will be an excellent addition to any prospective company in the near future.",
    name: "Wilson Savoy",
    title: "Musician, Pine Leaf Boys",
  },
  {
    image_url: jason_humphrey,
    desc: "If given the opportunity I would hire Trey for any of my coding needs. I know that he will be an excellent addition to any prospective company in the near future.",
    name: "Daniel Dekerlegand",
    title: "Senior Developer, Evolve",
  },
  {
    image_url: jason_humphrey,
    desc: "If given the opportunity I would hire Trey for any of my coding needs. I know that he will be an excellent addition to any prospective company in the near future.",
    name: "Janine Bonilla",
    title: "Marketing Director, Nasty",
  },
];

export const experiences = [
  {
    title: "Meteor JS Developer",
    company_name: "Torsh",
    icon: torsh,
    iconBg: "#E6DEDD",
    date: "April 2017 - August 2018",
    website_url: "https://www.torsh.co",
    points: [
      "Developed features in a large fullstack web application and separate corporate CMS website. Integrated 3rd party APIs into platform. Wrote server side CRUD methods and implementing frontend UI and UX.",
      "Architected features from design mocks. Communicated with UX designer to clarify feature behavior.",
      "Coordinated with other developers to complete sprints. Collaborated using version control to organize workflow. Discussed sprint progress during scrum meetings and engaged in peer reviews. Presented work during weekly demos.",
      "Corresponded with other developers via Slack and Google Hangouts. Collaborated on software development projects in realtime using screenshare software.",
      "Experienced with manual acceptance testing for large software releases. Automated testing experience. Tracked bugs by opening and resolving sprint cases.",
      "Drafted, composed, and edited technical documentation to meet purpose and standards.",
    ],
  },
  {
    title: "Founder/Sr. React JS Developer",
    company_name: "Vouzot",
    icon: vouzot,
    iconBg: "#7900B6",
    date: "August 2022 - Present",
    website_url: "https://www.vouzot.com",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    title: "Founder/Sr. React JS Developer",
    company_name: "Paste UI",
    icon: pasteui,
    iconBg: "#383E56",
    date: "Jan 2024 - Present",
    website_url: "https://www.pasteui.io",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
];

export const skillsData = [
  {
    skill_name: "Html 5",
    Image: "/html.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Css",
    Image: "/css.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "JavaScript",
    Image: "/js.png",
    width: 65,
    hight: 65,
  },
  {
    skill_name: "Tailwind CSS",
    Image: "/tailwind.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "React",
    Image: "/react.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Redux",
    Image: "/redux.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Tanstack React Query",
    Image: "/reactquery.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "TypeScript",
    Image: "/ts.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Next js 13",
    Image: "/next.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Next Auth",
    Image: "https://next-auth.js.org/img/logo/logo-sm.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "JSON Web Tocken",
    Image:
      "https://seeklogo.com/images/J/json-web-tokens-jwt-io-logo-C003DEC47A-seeklogo.com.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Framer Motion",
    Image: "/framer.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Stripe Payment",
    Image: "/stripe.webp",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Node js",
    Image: "/node-js.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Express js",
    Image: "/express.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Mongo db",
    Image: "/mongodb.png",
    width: 40,
    hight: 40,
  },
  {
    skill_name: "Firebase",
    Image: "/Firebase.png",
    width: 55,
    hight: 55,
  },
  {
    skill_name: "Postger SQL",
    Image: "/postger.png",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "My SQL",
    Image: "/mysql.png",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Prisma",
    Image: "/prisma.webp",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Graphql",
    Image: "/graphql.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "React Native",
    Image: "/ReactNative .png",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Docker",
    Image: "/docker.webp",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Figma",
    Image: "/figma.png",
    width: 50,
    hight: 50,
  },
  {
    skill_name: "Web Socket",
    Image: "https://avatars.githubusercontent.com/u/10566080?s=200&v=4",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Cloundary",
    Image: "https://cdn.worldvectorlogo.com/logos/cloudinary-2.svg",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Meteor js",
    Image: "https://raw.githubusercontent.com/gin-gonic/logo/master/color.png",
    width: 50,
    hight: 50,
  },
  {
    skill_name: "Git",
    Image: "https://git-scm.com/images/logos/downloads/Git-Icon-1788C.png",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Npm",
    Image: "https://authy.com/wp-content/uploads/npm-logo.png",
    width: 70,
    hight: 70,
  },
];

export const frontendSkills = [
  {
    skill_name: "Html 5",
    Image: "/html.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "CSS",
    Image: "/css.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "JavaScript",
    Image: "/js.png",
    width: 65,
    hight: 65,
  },
  {
    skill_name: "Tailwind CSS",
    Image: "/tailwind.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Material UI",
    Image: "/mui.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "React",
    Image: "/react.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Redux",
    Image: "/redux.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Tanstack React Query",
    Image: "/reactquery.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Zod",
    Image: "/reactquery.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Type Script",
    Image: "/ts.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Next js",
    Image: "/next.png",
    width: 80,
    hight: 80,
  },
];

export const backendSkills = [
  {
    skill_name: "Node js",
    Image: "/node-js.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Express js",
    Image: "/express.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Mongo db",
    Image: "/mongodb.png",
    width: 40,
    hight: 40,
  },
  {
    skill_name: "Fire base",
    Image: "/Firebase.png",
    width: 55,
    hight: 55,
  },
  {
    skill_name: "Postger SQL",
    Image: "/postger.png",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "My SQL",
    Image: "/mysql.png",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Prisma",
    Image: "/prisma.webp",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Graphql",
    Image: "/graphql.png",
    width: 80,
    hight: 80,
  },
];

export const fullstackSkills = [
  {
    skill_name: "React Native",
    Image: "/ReactNative .png",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Docker",
    Image: "/docker.webp",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Nigx",
    Image:
      "https://i0.wp.com/thinkground.studio/wp-content/uploads/2019/04/190415_Nginx-Logo.png?fit=423%2C401&ssl=1",
    width: 60,
    hight: 60,
  },
  {
    skill_name: "Figma",
    Image: "/figma.png",
    width: 50,
    hight: 50,
  },
  {
    skill_name: "Web Scoket",
    Image: "https://avatars.githubusercontent.com/u/10566080?s=200&v=4",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Gin gonic",
    Image: "https://raw.githubusercontent.com/gin-gonic/logo/master/color.png",
    width: 50,
    hight: 50,
  },
];

export const otherSkills = [
  {
    skill_name: "Next Auth",
    Image: "https://next-auth.js.org/img/logo/logo-sm.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Json Web Tocken",
    Image:
      "https://seeklogo.com/images/J/json-web-tokens-jwt-io-logo-C003DEC47A-seeklogo.com.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Framer Motion",
    Image: "/framer.png",
    width: 80,
    hight: 80,
  },
  {
    skill_name: "Stripe Payment",
    Image: "/stripe.webp",
    width: 80,
    hight: 80,
  },
];

export const other_skill2 = [
  {
    skill_name: "Cloundary",
    Image: "https://cdn.worldvectorlogo.com/logos/cloudinary-2.svg",
    width: 70,
    hight: 70,
  },

  {
    skill_name: "Git",
    Image: "https://git-scm.com/images/logos/downloads/Git-Icon-1788C.png",
    width: 70,
    hight: 70,
  },
  {
    skill_name: "Npm",
    Image: "https://authy.com/wp-content/uploads/npm-logo.png",
    width: 70,
    hight: 70,
  },
];
export const otherSkills3 = [
  {
    skill_name: "Go",
    Image: "/go.png",
    width: 60,
    hight: 60,
  },
];
